name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_limit: 10
          config_timezone: America/Argentina/Buenos_Aires
