name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: America/Argentina/Buenos_Aires

          base: header, activity, community, repositories
          base_indepth: no

          repositories_affiliations: owner, collaborator, organization_member

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_visibility: public
